[package]
name = "cuscuta-mock"
version.workspace = true
edition = "2024"

[dependencies]
anyhow.workspace = true
axum = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
cuscuta-common = { path = "../cuscuta-common" }
hex.workspace = true
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
