[package]
name = "cuscuta-common"
version.workspace = true
edition = "2024"

[lib]

[dependencies]
axum = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
futures = "0.3.34"
hex = { workspace = true }
redis = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["signal", "macros"] }
tokio-util = { workspace = true }
urlencoding = "2.1.3"

[dev-dependencies]
cuscuta-test = { path = "../cuscuta-test" }

[lints]
workspace = true
