[package]
name = "cuscuta-common"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
base64 = { workspace = true }
chrono = { workspace = true }
hex = { workspace = true }
redis = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["signal", "macros"] }
tokio-util = { workspace = true }
