[package]
name = "cuscuta-worker"
version.workspace = true
edition = "2024"

[dependencies]
cuscuta-common = { path = "../cuscuta-common" }
anyhow = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
redis = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["signal"] }
tokio-util = { workspace = true }

[lints]
workspace = true